export const CHANGE_TOTAL_CART = "CHANGE_TOTAL_CART";
export const ADD_PIZZA_CART = "ADD_PIZZA_CART";
export const EDIT_PIZZA_CART = "EDIT_PIZZA_CART";
export const DELETE_PIZZA_CART = "DELETE_PIZZA_CART";
export const TOGGLE_DRINK_CART = "TOGGLE_DRINK_CART";